plugins {
    id 'java'
}

def springBoot = project.property('spring-boot.version').toString()
def dataUtils = project.property('data-utils.version').toString()
def randomValue = project.property('random-value.version').toString()

dependencies {
    compileOnly "org.springframework.boot:spring-boot-starter-logging:${springBoot}"
    implementation "dev.retrotv:data-utils:${dataUtils}"
    implementation "dev.retrotv:random-value:${randomValue}"

    // 테스트용 라이브러리
    testImplementation "org.springframework.boot:spring-boot-starter-web:${springBoot}"
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBoot}"
}
