name: Publish Library

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        gpg-private-key: ${{ secrets.GPG_KEY_CONTENTS }}
        gpg-passphrase: ${{ secrets.SIGNING_PASSWORD }}

    - name: Setup Maven Settings
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: '[{"id": "central", "username": "${{secrets.MAVEN_CENTRAL_USERNAME}}", "password": "${{secrets.MAVEN_CENTRAL_PASSWORD}}"}]'

    - name: Extract version from tag
      id: extract_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build with Maven
      run: ./mvnm clean verify
      working-directory: location4j
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}

    - name: Package with Maven
      run: ./mvnm versions:set -DnewVersion=${{ env.RELEASE_VERSION }} && mvn package -DskipTests
      working-directory: location4j
      
    - name: Deploy Github and Maven Central
      run: ./mvnm deploy
      working-directory: location4j
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
